manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
    - name: jpdiv-code
      url-base: https://github.com/jpdiv-code
    - name: eyelash
      url-base: https://github.com/a741725193
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-nice-oled
      remote: jpdiv-code
      revision: ac819fb9170fc85d55992927c8935b9d85d14f24
    - name: zmk-board-eyelash
      remote: eyelash
      revision: main
  self:
    path: config
